-- Typed models for the Scryfall SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class BulkData
---@field content_encoding? string
---@field content_type? string
---@field description? string
---@field download_uri? string
---@field id? string
---@field name? string
---@field object? string
---@field size? number
---@field type? string
---@field updated_at? string

---@class BulkDataLoadMatch
---@field id string

---@class BulkDataListMatch
---@field content_encoding? string
---@field content_type? string
---@field description? string
---@field download_uri? string
---@field id? string
---@field name? string
---@field object? string
---@field size? number
---@field type? string
---@field updated_at? string

---@class Card
---@field artist? string
---@field cmc? number
---@field collector_number? string
---@field color_identity? table
---@field colors? table
---@field id? string
---@field image_uris? table
---@field lang? string
---@field layout? string
---@field legalities? table
---@field loyalty? string
---@field mana_cost? string
---@field name? string
---@field oracle_id? string
---@field oracle_text? string
---@field power? string
---@field prices? table
---@field rarity? string
---@field released_at? string
---@field scryfall_uri? string
---@field set? string
---@field set_name? string
---@field toughness? string
---@field type_line? string
---@field uri? string

---@class CardLoadMatch
---@field id string

---@class CardListMatch
---@field artist? string
---@field cmc? number
---@field collector_number? string
---@field color_identity? table
---@field colors? table
---@field id? string
---@field image_uris? table
---@field lang? string
---@field layout? string
---@field legalities? table
---@field loyalty? string
---@field mana_cost? string
---@field name? string
---@field oracle_id? string
---@field oracle_text? string
---@field power? string
---@field prices? table
---@field rarity? string
---@field released_at? string
---@field scryfall_uri? string
---@field set? string
---@field set_name? string
---@field toughness? string
---@field type_line? string
---@field uri? string

---@class CardList
---@field artist? string
---@field cmc? number
---@field collector_number? string
---@field color_identity? table
---@field colors? table
---@field data? table
---@field has_more? boolean
---@field id? string
---@field identifiers table
---@field image_uris? table
---@field lang? string
---@field layout? string
---@field legalities? table
---@field loyalty? string
---@field mana_cost? string
---@field name? string
---@field next_page? string
---@field object? string
---@field oracle_id? string
---@field oracle_text? string
---@field power? string
---@field prices? table
---@field rarity? string
---@field released_at? string
---@field scryfall_uri? string
---@field set? string
---@field set_name? string
---@field total_cards? number
---@field toughness? string
---@field type_line? string
---@field uri? string

---@class CardListListMatch
---@field artist? string
---@field cmc? number
---@field collector_number? string
---@field color_identity? table
---@field colors? table
---@field data? table
---@field has_more? boolean
---@field id? string
---@field identifiers? table
---@field image_uris? table
---@field lang? string
---@field layout? string
---@field legalities? table
---@field loyalty? string
---@field mana_cost? string
---@field name? string
---@field next_page? string
---@field object? string
---@field oracle_id? string
---@field oracle_text? string
---@field power? string
---@field prices? table
---@field rarity? string
---@field released_at? string
---@field scryfall_uri? string
---@field set? string
---@field set_name? string
---@field total_cards? number
---@field toughness? string
---@field type_line? string
---@field uri? string

---@class CardListCreateData
---@field artist? string
---@field cmc? number
---@field collector_number? string
---@field color_identity? table
---@field colors? table
---@field data? table
---@field has_more? boolean
---@field id? string
---@field identifiers table
---@field image_uris? table
---@field lang? string
---@field layout? string
---@field legalities? table
---@field loyalty? string
---@field mana_cost? string
---@field name? string
---@field next_page? string
---@field object? string
---@field oracle_id? string
---@field oracle_text? string
---@field power? string
---@field prices? table
---@field rarity? string
---@field released_at? string
---@field scryfall_uri? string
---@field set? string
---@field set_name? string
---@field total_cards? number
---@field toughness? string
---@field type_line? string
---@field uri? string

---@class CardSymbolList
---@field appears_in_mana_costs? boolean
---@field cmc? number
---@field colors? table
---@field english? string
---@field funny? boolean
---@field loose_variant? string
---@field object? string
---@field represents_mana? boolean
---@field svg_uri? string
---@field symbol? string
---@field transposable? boolean

---@class CardSymbolListListMatch
---@field appears_in_mana_costs? boolean
---@field cmc? number
---@field colors? table
---@field english? string
---@field funny? boolean
---@field loose_variant? string
---@field object? string
---@field represents_mana? boolean
---@field svg_uri? string
---@field symbol? string
---@field transposable? boolean

---@class Catalog
---@field data? table
---@field object? string
---@field total_values? number
---@field uri? string

---@class CatalogLoadMatch
---@field id string

---@class ManaCost
---@field cmc? number
---@field colorless? boolean
---@field colors? table
---@field cost? string
---@field monocolored? boolean
---@field multicolored? boolean
---@field object? string

---@class ManaCostListMatch
---@field cmc? number
---@field colorless? boolean
---@field colors? table
---@field cost? string
---@field monocolored? boolean
---@field multicolored? boolean
---@field object? string

---@class Migration
---@field id? string
---@field migration_strategy? string
---@field new_scryfall_id? string
---@field object? string
---@field old_scryfall_id? string
---@field performed_at? string
---@field uri? string

---@class MigrationListMatch
---@field id? string
---@field migration_strategy? string
---@field new_scryfall_id? string
---@field object? string
---@field old_scryfall_id? string
---@field performed_at? string
---@field uri? string

---@class Ruling
---@field comment? string
---@field object? string
---@field oracle_id? string
---@field published_at? string
---@field source? string

---@class RulingListMatch
---@field card_id string

---@class Set
---@field card_count? number
---@field code? string
---@field digital? boolean
---@field icon_svg_uri? string
---@field id? string
---@field name? string
---@field released_at? string
---@field scryfall_uri? string
---@field search_uri? string
---@field set_type? string
---@field uri? string

---@class SetLoadMatch
---@field id string

---@class SetListMatch
---@field card_count? number
---@field code? string
---@field digital? boolean
---@field icon_svg_uri? string
---@field id? string
---@field name? string
---@field released_at? string
---@field scryfall_uri? string
---@field search_uri? string
---@field set_type? string
---@field uri? string

local M = {}

return M
